name: Devendra Pal
email: Paldevendra93@gmail.com
phone: +91-9594304354
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/devendra-pal-7223b210a
description: Bookmark this to keep an eye on my project updates!
content:
  - title: About
    layout: text
    content: |
      Results-driven professional with 8+ years of combined experience, including as a Data Scientist specializing in Machine Learning, NLP, MLOps, Computer Vision, and GenAI, and as a Machine Design & Application Engineer in HVAC. Skilled in delivering impactful AI and ML solutions across various industries, with a strong track record in implementing and optimizing advanced machine learning models, particularly ML and Generative AI, to drive business outcomes and operational efficiency.
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Programming Languages
        description: Python
      - layout: left
        title: Machine Learning Algorithms
        description: Linear, Logistic, RF, XGB, etc.
      - layout: left
        title: Libraries & Tools
        description: Numpy, Pandas, Matplotlib, Hugging-face, Unsloth, Lang-chain, Crewal, etc.
      - layout: left
        title: Frameworks
        description: Flask, FastAPI
      - layout: left
        title: MLOps
        description: MLFlow, DVC, Docker, CI/CD, Git
      - layout: left
        title: Databases
        description: SQL
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Data Scientist
        sub_title: TCG Digital
        caption: June 2022 - Present
        description: |
          - Led multiple machine learning, NLP, and GenAI projects for clients, achieving significant improvements in process efficiency.
          - Key projects include NaSCN prediction, acid prediction for HPCL, and anti-money laundering case extraction using NLP techniques, fine-tuning Llama for Cata_LM in generative AI tasks and utilizing Retrieval-Augmented Generation (RAG) in Reliable AI solutions.
      - layout: left
        title: AI Engineer
        sub_title: Datten & Wissen
        caption: June 2021 - June 2022
        description: |
          - Developed computer vision models for mosquito detection and safety equipment detection in industrial environments.
          - Extracted critical information from legal documents using OCR and NLP techniques for clients like IIFL.
      - layout: left
        title: Junior Data Scientist
        sub_title: Prithvi.Ai
        caption: January 2021 - June 2021
        description: |
          - Worked on sensor data analysis for alarm prediction using Auto-encoder models.
          - Contributed to polymer quality prediction, delivering actionable insights.
      - layout: left
        title: Data Analyst & Application Engineer
        sub_title: Maico Ventilation India
        caption: January 2020 - July 2020
        description: |
          - Data Analysis of ventilation system.
          - Design & select the Ventilation equipment on the basis of requirements in project.
      - layout: left
        title: Application & Design Engineer
        sub_title: Euroclima India
        caption: October 2016 - January 2020
        description: |
          - Design the AHU, copper piping selection, fan selection etc.
          - Led projects in the AHU department from inception to completion, ensuring high-quality outcomes and adherence to project timelines.
      - layout: left
        title: Application Engineer
        sub_title: Sensicol Technology
        caption: July 2015 - October 2016
        description: |
          - Worked on Enquires, estimation, project execution etc.
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Cata_LM (GenAI)
        description: |
          Fine-tuned the Llama 3.1 model on lab data in the Alpaca format to determine the optimal proportions of Amorphous, Crystalline, and base metal for the Hydrocracking process, with the primary goal of assessing selectivity and activity based on these proportions and vice versa.
      - layout: left
        title: Reliable_AI (GenAI)
        description: |
          Built a predictive system to identify potential plant shutdown risks by analyzing data to forecast issues and pinpoint affected tags. Employed Llama 3.1 within a Retrieval-Augmented Generation (RAG) model to retrieve relevant solutions from historical data, enhancing issue resolution and minimizing downtime.
      - layout: left
        title: Sodium Sulphate and Sodium Thiocyanate Prediction (ML)
        description: |
          Implemented feature engineering, selection, and hyperparameter tuning to predict target variables using XGBoost and Random Forest.
      - layout: left
        title: IIFL Legal Documents Agreement (OCR, NLP)
        description: |
          Led a project with two main components: implemented an OCR system using the docTR engine for document processing and developed an NLP solution using regular expressions to extract client names, registration numbers, and property details.
  - title: Education
    layout: list
    content:
      - layout: left
        title: BE in Mechanical Engineering
        sub_title: Mumbai University
        description: |
  - title: Certifications
    layout: list
    content:
      - layout: left
        title: PGD in Data Science & AI
        sub_title: Edvancer
      - layout: left
        title: TCGMcube Certificate
        sub_title: TCG Digital
      - layout: left
        title: Data Science GenAI
        sub_title: Coursera
